name: Code-quality

on: [push]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E203,W503,W605"
          path: "."

  black:
    runs-on: ubuntu-latest
    name: Black formatter
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: runner / black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --diff --line-length 79 --check"
